version: '3.9'

services:
  docket-server:
    build:
      context: .
      dockerfile: Docket.Server/Dockerfile
    ports:
      - "44331:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  docket-client:
    build:
      context: .
      dockerfile: Docket.Client/Dockerfile
    ports:
      - "8080:44398"
    depends_on:
      - docket-server
